title: Civic Hacking Agency
description: Bringing technologists together to design, code and learn a new way to experience civics.
url: https://civichackingagency.org

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
#  - jekyll-paginate
markdown: kramdown

# 404
permalink: /404.html

# Date/time
date: "%B %-d, %Y"
timezone: America/Los_Angeles

# Defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      folder: "News"
      img-path: "posts"
      parent: "news"
      layout: "post"
      short: "true"
  - scope:
      path: "_events"
      type: "events"
    values:
      folder: "Events"
      img-path: "events"
      parent: "events"
      layout: "event"
      short: "true"
  - scope:
      path: "_projects"
      type: "projects"
    values:
      folder: "Projects"
      img-path: "projects"
      parent: "projects"
      layout: "project"
      short: "true"
  - scope:
      path: "_speakers"
      type: "speakers"
    values:
      folder: "Speakers"
      img-path: "speakers"
      parent: "speakers"
      layout: "speaker"
      short: "true"

# Collections
collections:
  posts:
    output: true
    permalink: /news/:title
  pages:
    output: true
    permalink: :title
  events:
    output: true
    permalink: /events/:title
  projects:
    output: true
    permalink: /projects/:title
  speakers:
    output: true
    permalink: /speakers/:title